"""Arabic-first interface copy for the Streamlit workspace."""

from __future__ import annotations

from typing import Any

DEFAULT_UI_LANGUAGE = "ar"
SUPPORTED_UI_LANGUAGES = ("ar", "en")


UI_COPY: dict[str, dict[str, str]] = {
    "ar": {
        "language": "اللغة",
        "language_ar": "العربية",
        "language_en": "English",
        "tagline": "مساعد زراعي عملي لعكار وريف لبنان",
        "intro": "اسأل عن الزراعة، العلوم، التكاليف، أو إدارة مشروعك بلغة بسيطة.",
        "login_heading": "معلومات زراعية أوضح وقرارات أفضل",
        "login_body": (
            "يساعدك RAISE في البحث ضمن المعرفة المراجَعة، وفهم المصادر، "
            "وإعداد خطط وجداول عملية."
        ),
        "login_safety": (
            "قد يخطئ الذكاء الاصطناعي. راجع مختصاً محلياً قبل أي قرار قد يؤثر "
            "في الصحة أو السلامة أو المبيدات أو البيطرة أو المال. لا ترفع معلومات حساسة."
        ),
        "login_note": (
            "سجّل الدخول بحساب Google موثّق لإنشاء مساحة خاصة. لا يستلم التطبيق "
            "كلمة مرور Google ولا يخزّنها."
        ),
        "continue_google": "المتابعة باستخدام Google",
        "privacy_policy": "سياسة الخصوصية",
        "user_agreement": "اتفاقية الاستخدام",
        "back_to_app": "العودة إلى التطبيق",
        "consent_title": "قبل أن تبدأ",
        "consent_notice": (
            "اقرأ اتفاقية الاستخدام وسياسة الخصوصية. استخدم معلومات عامة وغير حساسة فقط."
        ),
        "read_agreement": "اقرأ اتفاقية الاستخدام",
        "read_privacy": "اقرأ سياسة الخصوصية",
        "consent_terms": "أوافق على اتفاقية الاستخدام وأقرّ بأنني قرأت سياسة الخصوصية، الإصدار {version}.",
        "consent_processing": "أفهم أن سؤالي والسياق اللازم قد يُرسلان إلى مزوّد الذكاء الاصطناعي لإعداد الإجابة.",
        "consent_safety": "لن أرسل بيانات شخصية حساسة أو معلومات سرية أو مواد لا يحق لي مشاركتها.",
        "consent_age": "عمري 18 سنة على الأقل، أو أستخدم الخدمة بإشراف بالغ أو جهة مخوّلة.",
        "accept_continue": "أوافق وأتابع",
        "privacy_questions": "لأسئلة الخصوصية: {email}",
        "logout": "تسجيل الخروج",
        "new_chat": "محادثة جديدة",
        "search_chats": "ابحث في المحادثات",
        "recent_chats": "المحادثات الأخيرة",
        "no_search_results": "لا توجد محادثات مطابقة.",
        "new_conversation": "محادثة جديدة",
        "project": "المشروع",
        "no_project": "من دون مشروع",
        "manage_projects": "إدارة المشاريع",
        "settings": "الإعدادات",
        "pilot_admin": "مسؤول النظام",
        "whatsapp_identity": "حساب WhatsApp",
        "queries_left": "متبقّي اليوم: {count} سؤال",
        "answer_settings": "طريقة الإجابة",
        "privacy_data": "الخصوصية والبيانات",
        "response_mode": "مستوى الإجابة",
        "ai_model": "نموذج الذكاء الاصطناعي",
        "conversation_style": "طريقة طرح الأسئلة التوضيحية",
        "save_settings": "حفظ الإعدادات",
        "settings_saved": "تم حفظ الإعدادات.",
        "mode_quick": "سريع",
        "mode_standard": "متوازن",
        "mode_deep": "متعمّق",
        "mode_source_only": "من المصادر فقط",
        "mode_quick_help": "إجابة قصيرة للأسئلة اليومية أو عند ضعف الإنترنت.",
        "mode_standard_help": "توازن مناسب بين السرعة والتفصيل والمصادر. وهو الخيار المقترح.",
        "mode_deep_help": "بحث وتحليل أوسع للمقارنة والتخطيط والقرارات المركّبة.",
        "mode_source_only_help": "إجابة محصورة بالمعلومات الموجودة في قاعدة المعرفة المراجَعة.",
        "style_auto": "تلقائي",
        "style_guided": "إرشاد خطوة بخطوة",
        "style_direct": "إجابة مباشرة",
        "style_auto_help": "يسأل سؤالاً قصيراً فقط عندما تكون المعلومة الناقصة مهمة.",
        "style_guided_help": "يساعدك على توضيح حاجتك بسؤال قصير في كل مرة.",
        "style_direct_help": "يفترض ما هو معقول ويجيب مباشرة مع توضيح افتراضاته.",
        "model_help": "يمكنك تجربة نماذج مختلفة خلال الاختبار. اختيارك لا يغيّر قواعد الأمان أو المصادر.",
        "model_gemini_help": "سريع ومناسب للأسئلة اليومية والصور.",
        "model_mimo_help": "فعّال للأسئلة اليومية وفهم الصور.",
        "model_minimax_help": "متوازن للتحليل وإعداد الملفات العملية.",
        "model_kimi_help": "تحليل أعمق، لكنه أبطأ وقد تكون كلفته أعلى.",
        "agreement_version": "الإصدار {version} · الحفظ حتى {days} يوماً",
        "read_legal": "قراءة المستندات القانونية",
        "choose_document": "اختر المستند",
        "download_data": "تنزيل نسخة من بياناتي (JSON)",
        "download_note": "يمكن تنزيل الملفات المرفوعة والملفات التي أنشأها المساعد من بطاقاتها داخل التطبيق.",
        "delete_account_instruction": "لحذف الحساب نهائياً، اكتب: احذف حسابي",
        "delete_account": "حذف حسابي ومحتواي الخاص",
        "delete_account_phrase": "احذف حسابي",
        "delete_failed": "توقف الحذف لأن ملفاً خاصاً لم يُحذف. حاول مجدداً أو تواصل مع مسؤول الخصوصية.",
        "create_project": "إنشاء مشروع",
        "project_name": "اسم المشروع",
        "project_instructions": "تعليمات المشروع",
        "project_instructions_help": "مثال: نوع المحصول، المنطقة، أو طريقة عرض النتائج. لا يمكن لهذه التعليمات تجاوز قواعد الأمان.",
        "create": "إنشاء",
        "current_project": "المشروع الحالي",
        "edit_project": "تعديل المشروع",
        "name": "الاسم",
        "instructions": "التعليمات",
        "save_project": "حفظ المشروع",
        "project_saved": "تم حفظ المشروع.",
        "reference_files": "ملفات المشروع المرجعية",
        "upload_reference": "أضف ملفات عامة وغير حساسة",
        "upload_reference_help": "PDF أو DOCX أو TXT أو CSV أو XLSX، بحد أقصى 10 MB للملف.",
        "process_files": "إضافة الملفات إلى المشروع",
        "processed_files": "تمت إضافة {count} ملف/ملفات.",
        "download": "تنزيل",
        "delete": "حذف",
        "unavailable": "غير متاح",
        "no_documents": "لا توجد ملفات في هذا المشروع بعد.",
        "delete_project_confirm": "أفهم أن حذف المشروع سيحذف محادثاته وملفاته الخاصة.",
        "delete_project": "حذف المشروع نهائياً",
        "project_delete_failed": "توقف حذف المشروع لأن ملفاً خاصاً لم يُحذف. حاول مجدداً أو تواصل مع المسؤول.",
        "chat_options": "خيارات المحادثة",
        "chat_title": "عنوان المحادثة",
        "rename": "تغيير الاسم",
        "archive_chat": "أرشفة المحادثة",
        "delete_chat_confirm": "أفهم أن حذف المحادثة نهائي.",
        "delete_chat": "حذف المحادثة",
        "chat_delete_failed": "توقف حذف المحادثة لأن ملفاً خاصاً لم يُحذف. حاول مجدداً أو تواصل مع المسؤول.",
        "project_context": "ضمن مشروع: {name}",
        "standalone_chat": "محادثة مستقلة",
        "safety_short": "راجع مختصاً قبل القرارات عالية الخطورة. لا ترسل بيانات حساسة.",
        "welcome_title": "كيف يمكنني مساعدتك اليوم؟",
        "welcome_body": "اكتب سؤالك كما تتحدث عادةً. سأطلب توضيحاً فقط إذا كان ضرورياً.",
        "try_question": "أمثلة يمكنك تجربتها",
        "suggestion_1": "حضّر لي قائمة فحص قبل زراعة البطاطا في عكار.",
        "suggestion_2": "كيف أحسب كلفة مشروع زراعي صغير ونقطة التعادل؟",
        "suggestion_3": "اشرح لي فائدة تجميع مياه الأمطار للمواشي بطريقة علمية بسيطة.",
        "suggestion_4": "الخيار في البيت البلاستيكي يذبل. ما المعلومات التي تحتاجها مني؟",
        "composer_placeholder": "اكتب سؤالك هنا…",
        "composer_image_note": "يمكنك إرفاق صورة JPG أو PNG حتى 5 MB. الصورة تساعد في الفهم لكنها لا تكفي لتشخيص نهائي.",
        "composer_no_image": "هذا النموذج لا يقبل الصور حالياً. يمكنك اختيار نموذج آخر من الإعدادات.",
        "image_only_prompt": "ساعدني على فهم ما يظهر في هذه الصورة، واذكر ما تحتاجه مني قبل إعطاء توصية.",
        "image_invalid_size": "يجب أن تكون الصورة غير فارغة وألا يتجاوز حجمها 5 MB.",
        "image_invalid_type": "يمكن إرفاق صور JPG أو PNG فقط.",
        "image_dimensions": "أبعاد الصورة كبيرة جداً.",
        "image_invalid": "تعذر قراءة الصورة. جرّب صورة JPG أو PNG أخرى.",
        "image_normalized_size": "أصبح حجم الصورة أكبر من 5 MB بعد تجهيزها.",
        "attached_unavailable": "الصورة المرفقة لم تعد متاحة.",
        "regenerate": "إعادة الإجابة",
        "checking": "أراجع السؤال والمعلومات والمصادر المناسبة…",
        "sources": "المصادر والأدلة ({count})",
        "source_status": "الحالة: {status} · نوع الدليل: {evidence}",
        "user_document": "ملف أضافه المستخدم: {title}",
        "user_document_notice": "هذا الملف من المستخدم وليس مصدراً رسمياً معتمداً.",
        "trusted_source": "مصدر موثوق ومحدّث",
        "model_source": "رابط اقترحه النموذج",
        "tools_used": "الأدوات المستخدمة: {tools}",
        "download_artifact": "تنزيل {filename}",
        "artifact_unavailable": "الملف الذي أنشأه المساعد لم يعد متاحاً.",
        "helpful": "مفيد",
        "not_helpful": "غير مفيد",
        "feedback_saved": "شكراً، تم تسجيل رأيك.",
        "copy_answer": "نسخ الإجابة",
        "voice": "الاستماع إلى الإجابة",
        "voice_notice": "سيُرسل نص الإجابة إلى خدمة Microsoft Edge لتحويله إلى صوت.",
        "generate_audio": "إنشاء الصوت",
        "audio_failed": "تعذر إنشاء الصوت.",
        "pilot_metrics": "مؤشرات الاختبار",
    },
    "en": {
        "language": "Language",
        "language_ar": "العربية",
        "language_en": "English",
        "tagline": "Practical agricultural support for Akkar and rural Lebanon",
        "intro": "Ask about farming, science, costs, or project management in plain language.",
        "login_heading": "Clearer agricultural information, better decisions",
        "login_body": "RAISE can search reviewed knowledge, explain sources, and create practical plans and tables.",
        "login_safety": "AI can be wrong. Consult a qualified local professional before decisions affecting health, safety, pesticides, veterinary care, or money. Do not upload sensitive information.",
        "login_note": "Sign in with a verified Google account to create a private workspace. The application never receives or stores your Google password.",
        "continue_google": "Continue with Google",
        "privacy_policy": "Privacy Policy",
        "user_agreement": "User Agreement",
        "back_to_app": "Back to the application",
        "consent_title": "Before you begin",
        "consent_notice": "Read the User Agreement and Privacy Policy. Submit only public or non-sensitive information.",
        "read_agreement": "Read the User Agreement",
        "read_privacy": "Read the Privacy Policy",
        "consent_terms": "I accept the User Agreement and acknowledge the Privacy Policy, version {version}.",
        "consent_processing": "I understand that my question and necessary context may be sent to the configured AI provider to generate an answer.",
        "consent_safety": "I will not submit sensitive personal data, confidential information, or material I am not authorized to share.",
        "consent_age": "I am at least 18, or I am using the service under approved adult or institutional supervision.",
        "accept_continue": "Accept and continue",
        "privacy_questions": "Privacy questions: {email}",
        "logout": "Log out",
        "new_chat": "New chat",
        "search_chats": "Search chats",
        "recent_chats": "Recent chats",
        "no_search_results": "No matching conversations.",
        "new_conversation": "New conversation",
        "project": "Project",
        "no_project": "No project",
        "manage_projects": "Manage projects",
        "settings": "Settings",
        "pilot_admin": "Administrator",
        "whatsapp_identity": "WhatsApp identity",
        "queries_left": "{count} questions left today",
        "answer_settings": "Answer preferences",
        "privacy_data": "Privacy and data",
        "response_mode": "Answer depth",
        "ai_model": "AI model",
        "conversation_style": "Clarification style",
        "save_settings": "Save settings",
        "settings_saved": "Settings saved.",
        "mode_quick": "Quick",
        "mode_standard": "Balanced",
        "mode_deep": "Deep",
        "mode_source_only": "Sources only",
        "mode_quick_help": "A short answer for routine questions or slower connections.",
        "mode_standard_help": "A practical balance of speed, detail, and sources. Recommended for most questions.",
        "mode_deep_help": "Broader research and analysis for comparison, planning, and complex decisions.",
        "mode_source_only_help": "Restricts the answer to information in the reviewed knowledge base.",
        "style_auto": "Automatic",
        "style_guided": "Step-by-step guidance",
        "style_direct": "Direct answer",
        "style_auto_help": "Asks one short question only when missing information materially matters.",
        "style_guided_help": "Helps narrow the need with one short question at a time.",
        "style_direct_help": "Uses reasonable assumptions and answers directly while stating them.",
        "model_help": "You can compare models during the trial. Your choice does not change safety or evidence rules.",
        "model_gemini_help": "Fast and suitable for everyday questions and images.",
        "model_mimo_help": "Efficient for routine questions and image understanding.",
        "model_minimax_help": "Balanced for analysis and practical file generation.",
        "model_kimi_help": "Deeper analysis, but slower and potentially more expensive.",
        "agreement_version": "Version {version} · retained for up to {days} days",
        "read_legal": "Read legal documents",
        "choose_document": "Choose a document",
        "download_data": "Download my data (JSON)",
        "download_note": "Uploaded files and assistant-generated files can be downloaded from their cards in the application.",
        "delete_account_instruction": "To permanently delete the account, type: DELETE MY ACCOUNT",
        "delete_account": "Delete my account and private content",
        "delete_account_phrase": "DELETE MY ACCOUNT",
        "delete_failed": "Deletion stopped because a private file could not be removed. Retry or contact the privacy administrator.",
        "create_project": "Create a project",
        "project_name": "Project name",
        "project_instructions": "Project instructions",
        "project_instructions_help": "For example: crop, area, or preferred output. These instructions cannot override safety rules.",
        "create": "Create",
        "current_project": "Current project",
        "edit_project": "Edit project",
        "name": "Name",
        "instructions": "Instructions",
        "save_project": "Save project",
        "project_saved": "Project saved.",
        "reference_files": "Project reference files",
        "upload_reference": "Add public or non-sensitive files",
        "upload_reference_help": "PDF, DOCX, TXT, CSV, or XLSX; maximum 10 MB per file.",
        "process_files": "Add files to project",
        "processed_files": "Added {count} file(s).",
        "download": "Download",
        "delete": "Delete",
        "unavailable": "Unavailable",
        "no_documents": "No project files yet.",
        "delete_project_confirm": "I understand that deleting this project will delete its chats and private files.",
        "delete_project": "Permanently delete project",
        "project_delete_failed": "Project deletion stopped because a private file could not be removed. Retry or contact the administrator.",
        "chat_options": "Chat options",
        "chat_title": "Chat title",
        "rename": "Rename",
        "archive_chat": "Archive chat",
        "delete_chat_confirm": "I understand that deleting this chat is permanent.",
        "delete_chat": "Delete chat",
        "chat_delete_failed": "Chat deletion stopped because a private file could not be removed. Retry or contact the administrator.",
        "project_context": "Project: {name}",
        "standalone_chat": "Standalone chat",
        "safety_short": "Consult a professional for high-risk decisions. Do not submit sensitive data.",
        "welcome_title": "How can I help today?",
        "welcome_body": "Ask naturally. I will request clarification only when it is genuinely needed.",
        "try_question": "Ideas to try",
        "suggestion_1": "Create a field checklist before planting potatoes in Akkar.",
        "suggestion_2": "How do I calculate a small farm project's cost and break-even point?",
        "suggestion_3": "Explain the evidence for rainwater harvesting for livestock in simple terms.",
        "suggestion_4": "My greenhouse cucumbers are wilting. What information do you need from me?",
        "composer_placeholder": "Message RAISE…",
        "composer_image_note": "Attach one JPG or PNG image up to 5 MB. An image can support understanding but cannot provide a definitive diagnosis.",
        "composer_no_image": "This model does not currently accept images. Choose another model in Settings.",
        "image_only_prompt": "Help me understand what this image shows, and tell me what you need before giving a recommendation.",
        "image_invalid_size": "The image must be non-empty and no larger than 5 MB.",
        "image_invalid_type": "Only JPG and PNG images are accepted.",
        "image_dimensions": "The image dimensions are too large.",
        "image_invalid": "The image could not be read. Try another JPG or PNG image.",
        "image_normalized_size": "The prepared image is larger than 5 MB.",
        "attached_unavailable": "The attached image is no longer available.",
        "regenerate": "Regenerate",
        "checking": "Reviewing the question, relevant information, and sources…",
        "sources": "Sources and evidence ({count})",
        "source_status": "Status: {status} · Evidence: {evidence}",
        "user_document": "User-provided file: {title}",
        "user_document_notice": "This is user-provided material, not an approved authority.",
        "trusted_source": "Trusted current source",
        "model_source": "Model-suggested link",
        "tools_used": "Tools used: {tools}",
        "download_artifact": "Download {filename}",
        "artifact_unavailable": "An assistant-generated file is no longer available.",
        "helpful": "Helpful",
        "not_helpful": "Not helpful",
        "feedback_saved": "Thank you. Your feedback was recorded.",
        "copy_answer": "Copy answer",
        "voice": "Listen to answer",
        "voice_notice": "The answer text will be sent to Microsoft Edge to generate audio.",
        "generate_audio": "Generate audio",
        "audio_failed": "Audio could not be generated.",
        "pilot_metrics": "Pilot metrics",
    },
}


MODEL_DESCRIPTION_KEYS = {
    "google/gemini-3.6-flash": "model_gemini_help",
    "xiaomi/mimo-v2.5": "model_mimo_help",
    "minimax/minimax-m3": "model_minimax_help",
    "moonshotai/kimi-k3": "model_kimi_help",
}


def normalize_ui_language(value: str | None) -> str:
    """Return a supported UI language, defaulting to Arabic."""

    return value if value in SUPPORTED_UI_LANGUAGES else DEFAULT_UI_LANGUAGE


def text(language: str, key: str, **values: Any) -> str:
    """Get localized interface copy with an English fallback."""

    language = normalize_ui_language(language)
    template = UI_COPY.get(language, {}).get(key) or UI_COPY["en"].get(key)
    if template is None:
        raise KeyError(f"Unknown UI copy key: {key}")
    return template.format(**values) if values else template
